CREATE TABLE IF NOT EXISTS `drug_instructions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `active` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=35//
INSERT INTO `drug_instructions` (`id`, `name`, `active`) VALUES
(1, 'Warning. May cause drowsiness', 1),
(2, 'Warning. May cause drowsiness. If affected to do not drive or operate machinery.Avoid alcoholic drink', 1),
(3, 'Warning. May cause drowsiness. If affected to do not drive or operate machinery.', 1),
(4, 'Warning. Avoid alcoholic drink', 1),
(5, 'Do not take indigestion remedies at the same time of the day as this medicine', 1),
(6, 'Do not take indigestion remedies or medicines containing Iron or Zinc at the same time of a day as this medicine', 1),
(7, 'Do not take milk, indigestion remedies, or medicines containing Iron or Zinc at the same time of day as this medicine', 1),
(8, 'Do not stop taking this medicine except on your doctor''s advice', 1),
(9, 'Take at regular intervals. Complete the prescribed course unless otherwise directed', 1),
(10, 'Warning. Follow the printed instruction you have been given with this medicine', 1),
(11, 'Avoid exposure of skin to direct sunlight or sun lamps', 1),
(12, 'Do not take anything containing aspirin while taking  this medicine', 1),
(13, 'Dissolve or mix with water before taking', 1),
(14, 'This medicine may colour the urine', 1),
(15, 'Caution flammable: Keep away from fire or flames', 1),
(16, 'Allow to dissolve under the tongue. Do not transfer from this container. Keep tightly closed. Discard 8 weeks after opening.', 1),
(17, 'Do not take more than??.in 24 hours', 1),
(18, 'Do not take more than ?..in 24 hours or?. In any one week', 1),
(19, 'Warning. Causes drowsiness which may continue the next day. If affected do not drive or operate machinery. Avoid alcoholic drink', 1),
(20, '??..with or after food', 1),
(21, '???.half to one hour after food', 1),
(22, '????..an hour before food or on an empty stomach', 1),
(23, '???.an hour before food or on an empty stomach', 1),
(24, '???. sucked or chewed', 1),
(25, '??? swallowed whole, not chewed', 1),
(26, '???dissolved under the tongue', 1),
(27, '????with plenty of water', 1),
(28, 'To be spread thinly?..', 1),
(29, 'Do not take more than  2 at any one time. Do not take more than 8 in 24 hours', 1),
(30, 'Do not take with any other paracetamol products.', 1),
(31, 'Contains aspirin and paracetamol. Do not take with any other paracetamol products', 1),
(32, 'Contains aspirin', 1),
(33, 'contains an apirin-like medicine', 1),
(34, 'Avoid a lot of fatty meals together with efavirenz', 1)//